app:
  spot_base_url: ${SPOT_BASE_URL}
  spot_api_key: ${SPOT_API_KEY}
  spot_secret_key: ${SPOT_SECRET_KEY}
  futures_base_url: ${FUTURES_BASE_URL}
  futures_api_key: ${FUTURES_API_KEY}
  futures_secret_key: ${FUTURES_SECRET_KEY}